base:
  objects:
    String:
      type: PRIMITIVE
      description: A string

    Integer:
      type: PRIMITIVE
      description: An integer

    Float:
      type: PRIMITIVE
      description: A float

    Boolean:
      type: PRIMITIVE
      description: Either ``true`` or ``false``

    Map:
      type: PRIMITIVE
      description: A map

    List:
      type: PRIMITIVE
      description: A list

    Set:
      type: PRIMITIVE
      description: A set

    Expression:
      type: PRIMITIVE
      description: An expression

    WeightedList:
      type: MULTI_TYPE
      description: A weighted list

    NoiseSampler:
      type: TEMPLATED
      description: |
        .. seealso::

            :doc:`/config/development/noise/index`

            :ref:`Config Documentation Format <config-documentation-format>` :octicon:`chevron-right`

        A sampler is a config defined function that world positions and the world seed to a set
        of output values.

        A 'sample' is defined as the value produced by a single calculation provided by a sampler. A collective set of
        samples is regarded as 'noise'.

        Noise produced by noise samplers :doc:`determine some kind of behaviour </config/development/noise/use>` for each block or column. This behaviour
        is dependent on the context of the sampler definition. 

    Range:
      type: MULTI_TYPE
      description: A range
      types:
        int:
          description: When a range is declared as an int ...
        map:
          description: When a range is declared as a map ...
          params:
            min:
              type: Integer
            max:
              type: Integer

    BiomeProvider:
      type: TEMPLATED

    Biome:
      type: REGISTRY_KEY
      description: |
        A Terra biome ID.

    Palette:
      type: MULTI_TYPE
      description: |
        A Terra palette ID. Palettes are added via the :doc:`/config/documentation/configs/PALETTE` config type.

    Feature:
      type: MULTI_TYPE
      description: A feature ID
      types:
        string:

    Structure:
      type: MULTI_TYPE
      description: A structure ID
      types:
        string:

    Block:
      type: MULTI_TYPE
      types:
        string:

    Distributor:
      type: TEMPLATED

    Locator:
      type: TEMPLATED

    GenerationStage:
      type: TEMPLATED

    Tag:
      type: MULTI_TYPE
      description: A tag
      types:
        string:

    PlatformBiome:
      type: MULTI_TYPE
      description: A platform biome
      types:
        string:

    ChunkGenerator:
      type: MULTI_TYPE

  configs:
    pack.yml:
      description: |
        The config pack manifest

  config-templates:
    pack.yml:
      base:
        params:
          id:
            type: String
          author:
            type: String
            default: Anon Y. Mous
          stages:
            type: List<GenerationStage>
          version:
            type: Version
          generator:
            type: ChunkGenerator
          biomes:
            type: BiomeProvider
