generation-stage-feature:
  templates:
    GenerationStage:
      FEATURE:
        params:
          id:
            type: String
          resolution:
            type: Integer
            default: "4"
  config-templates:
    BIOME:
      params:
        features.<stage id>:
          type: List<Feature>

